# Generated by Django 3.0.8 on 2020-08-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScotInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_email', models.CharField(max_length=100, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
    ]
